"""initial schema

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00
"""
from alembic import op
import sqlalchemy as sa

revision = '001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('email', sa.String(150), unique=True, nullable=False),
        sa.Column('password', sa.String(255), nullable=False),
        sa.Column('role', sa.String(20), server_default='student'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('avatar_url', sa.String(500)),
        sa.Column('bio', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('courses',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('total_sessions', sa.Integer(), server_default='0'),
        sa.Column('category', sa.String(50)),
        sa.Column('thumbnail_url', sa.String(500)),
        sa.Column('prerequisite_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('enrollments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id')),
        sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('completed', sa.Boolean(), server_default='false'),
        sa.UniqueConstraint('user_id', 'course_id'),
    )
    op.create_table('sessions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('instructor', sa.String(100)),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=True),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('duration_hrs', sa.Numeric(4, 2)),
        sa.Column('status', sa.String(20), server_default='upcoming'),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('attendance',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('session_id', sa.Integer(), sa.ForeignKey('sessions.id'), nullable=False),
        sa.Column('check_in', sa.DateTime(timezone=True)),
        sa.Column('check_out', sa.DateTime(timezone=True)),
        sa.Column('hours_spent', sa.Numeric(4, 2), server_default='0'),
        sa.Column('status', sa.String(20), server_default='absent'),
        sa.UniqueConstraint('user_id', 'session_id'),
    )
    op.create_table('tests',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=True),
        sa.Column('pass_mark', sa.Integer(), server_default='60'),
        sa.Column('duration_min', sa.Integer(), server_default='30'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('questions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('test_id', sa.Integer(), sa.ForeignKey('tests.id'), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('option_a', sa.String(300)),
        sa.Column('option_b', sa.String(300)),
        sa.Column('option_c', sa.String(300)),
        sa.Column('option_d', sa.String(300)),
        sa.Column('correct_opt', sa.String(1)),
        sa.Column('marks', sa.Integer(), server_default='1'),
    )
    op.create_table('test_results',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('test_id', sa.Integer(), sa.ForeignKey('tests.id'), nullable=False),
        sa.Column('score', sa.Integer(), server_default='0'),
        sa.Column('total_marks', sa.Integer(), server_default='0'),
        sa.Column('percentage', sa.Numeric(5, 2), server_default='0'),
        sa.Column('passed', sa.Boolean(), server_default='false'),
        sa.Column('attempt_no', sa.Integer(), server_default='1'),
        sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('answers', sa.Text()),
    )
    op.create_table('user_answers',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('result_id', sa.Integer(), sa.ForeignKey('test_results.id'), nullable=False),
        sa.Column('question_id', sa.Integer(), sa.ForeignKey('questions.id'), nullable=False),
        sa.Column('chosen_opt', sa.String(1)),
        sa.Column('is_correct', sa.Boolean(), server_default='false'),
    )
    op.create_table('feedback',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('session_id', sa.Integer(), sa.ForeignKey('sessions.id'), nullable=False),
        sa.Column('overall_rating', sa.SmallInteger()),
        sa.Column('instructor_rating', sa.SmallInteger()),
        sa.Column('content_rating', sa.SmallInteger()),
        sa.Column('pace_rating', sa.SmallInteger()),
        sa.Column('comments', sa.Text()),
        sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('notifications',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('message', sa.Text()),
        sa.Column('type', sa.String(30), server_default='info'),
        sa.Column('is_read', sa.Boolean(), server_default='false'),
        sa.Column('link', sa.String(200)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table('lessons',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=False),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('video_url', sa.String(500)),
        sa.Column('content_type', sa.String(30), server_default='video'),
        sa.Column('duration_min', sa.Integer(), server_default='0'),
        sa.Column('sort_order', sa.Integer(), server_default='0'),
        sa.Column('is_free', sa.Boolean(), server_default='false'),
        sa.Column('attachment_url', sa.String(500)),
        sa.Column('attachment_name', sa.String(200)),
        sa.Column('unlock_after_lesson_id', sa.Integer(), sa.ForeignKey('lessons.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('lesson_progress',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('lesson_id', sa.Integer(), sa.ForeignKey('lessons.id'), nullable=False),
        sa.Column('completed', sa.Boolean(), server_default='false'),
        sa.Column('progress_pct', sa.Integer(), server_default='0'),
        sa.Column('last_position', sa.Integer(), server_default='0'),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint('user_id', 'lesson_id'),
    )
    op.create_table('discussions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('lesson_id', sa.Integer(), sa.ForeignKey('lessons.id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('parent_id', sa.Integer(), sa.ForeignKey('discussions.id'), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_answer', sa.Boolean(), server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('assignments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=False),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('due_date', sa.DateTime(timezone=True)),
        sa.Column('max_score', sa.Integer(), server_default='100'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('file_url', sa.String(500)),
        sa.Column('file_name', sa.String(200)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('submissions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('assignment_id', sa.Integer(), sa.ForeignKey('assignments.id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('file_url', sa.String(500)),
        sa.Column('comments', sa.Text()),
        sa.Column('score', sa.Integer()),
        sa.Column('graded', sa.Boolean(), server_default='false'),
        sa.Column('feedback', sa.Text()),
        sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('graded_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('assignment_id', 'user_id'),
    )
    op.create_table('notes',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('lesson_id', sa.Integer(), sa.ForeignKey('lessons.id'), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('video_timestamp', sa.Integer(), server_default='0'),
        sa.Column('is_bookmark', sa.Boolean(), server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('announcements',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('author_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=True),
        sa.Column('is_pinned', sa.Boolean(), server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('reviews',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=False),
        sa.Column('rating', sa.SmallInteger(), nullable=False),
        sa.Column('comment', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint('user_id', 'course_id'),
    )
    op.create_table('learning_paths',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('title', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('thumbnail_url', sa.String(500)),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('learning_path_courses',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('path_id', sa.Integer(), sa.ForeignKey('learning_paths.id'), nullable=False),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=False),
        sa.Column('sort_order', sa.Integer(), server_default='0'),
    )
    op.create_table('learning_path_enrollments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('path_id', sa.Integer(), sa.ForeignKey('learning_paths.id'), nullable=False),
        sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('wishlists',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('course_id', sa.Integer(), sa.ForeignKey('courses.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint('user_id', 'course_id'),
    )
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('entity_type', sa.String(50)),
        sa.Column('entity_id', sa.Integer()),
        sa.Column('details', sa.Text()),
        sa.Column('ip_address', sa.String(45)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

def downgrade():
    for t in ['audit_logs','wishlists','learning_path_enrollments','learning_path_courses','learning_paths','reviews','announcements','notes','submissions','assignments','discussions',
              'lesson_progress','lessons','notifications','feedback','user_answers','test_results',
              'questions','tests','attendance','sessions','enrollments','courses','users']:
        op.drop_table(t)
